# Generated by Django 5.0.3 on 2024-09-18 06:56

import django.db.models.deletion
import red_book_server.models.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=128, unique=True)),
            ],
            options={
                'db_table': '"category"',
            },
        ),
        migrations.CreateModel(
            name='RedBookItem',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256, unique=True)),
                ('description', models.TextField(max_length=1024, unique=True)),
                ('image_url', models.URLField()),
                ('count', models.IntegerField(validators=[red_book_server.models.validators.check_positive_number])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_book_server.category')),
            ],
            options={
                'db_table': '"red_book_item"',
                'unique_together': {('name', 'description')},
            },
        ),
    ]
