# Generated by Django 5.0.3 on 2024-09-18 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_book_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedBookLocation',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': '"location"',
            },
        ),
        migrations.AddField(
            model_name='redbookitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='red_book_server.redbooklocation'),
        ),
    ]
