# Generated by Django 5.0.3 on 2024-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_book_server', '0002_redbooklocation_redbookitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='redbookitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
