# Generated by Django 5.0.3 on 2024-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_book_server', '0003_redbookitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redbookitem',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='redbookitem',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
