# Generated by Django 5.0.3 on 2024-09-18 15:50

import django.db.models.deletion
import red_book_server.models.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_book_server', '0004_remove_redbookitem_image_url_alter_redbookitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedBookItemRequest',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256, unique=True)),
                ('description', models.TextField(max_length=1024, unique=True)),
                ('image', models.ImageField(upload_to='media')),
                ('count', models.IntegerField(validators=[red_book_server.models.validators.check_positive_number])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_book_server.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='red_book_server.redbooklocation')),
            ],
            options={
                'db_table': '"red_book_item_request"',
            },
        ),
    ]
